apiVersion: v1
kind: Secret
metadata:
  name: java-starter-boilerplate-secret
type: Opaque
stringData:
  DB_USER: "starter"
  DB_PASSWORD: "change-me"
  STORAGE_S3_ACCESS_KEY: "minioadmin"
  STORAGE_S3_SECRET_KEY: "minioadmin"
